server:
  port: 8088
---
spring:
  cloud:
    config:
      name: configtest-dev
  config:
#    ???? ?? Uri]
#    ?? ?? ?  ??? ?? ?? Fetching config from server at : http://localhost:9900
#    ??? ?? ?? ?? ??? ???? ??????? ????? ?? ?????
#    ?? ??? ???? ?? ???? ????? ?????? Actuaor??.
    import: optional:configserver:http://localhost:9900

---
# actuator
# ??? uri? ??? ??????
# actuator/refresh post???? ??? ??? ????? refresh ??? ????.
management:
  endpoints:
    web:
      exposure:
        include: refresh